# Generated by Django 5.0.3 on 2026-10-02 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='عنوان IP')),
                ('governorate', models.CharField(max_length=100, verbose_name='المحافظة')),
                ('visit_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الزيارة')),
            ],
            options={
                'verbose_name': 'سجل الزيارة',
                'verbose_name_plural': 'سجلات الزوار',
            },
        ),
    ]
