# Generated by Django 5.0.3 on 2026-10-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(default='اليمن', max_length=100, verbose_name='الدولة'),
        ),
    ]
