# Generated by Django 6.1.1 on 2026-10-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_visitorlog_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['-visit_time'], 'verbose_name': 'سجل الزيارة', 'verbose_name_plural': 'سجلات الزوار'},
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='accuracy',
            field=models.FloatField(default=0.0, verbose_name='دقة الموقع'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='المتصفح'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='device_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع الجهاز'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='العرض'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='الطول'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نظام التشغيل'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='referrer',
            field=models.URLField(blank=True, null=True, verbose_name='الصفحة السابقة'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='governorate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المحافظة'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP'),
        ),
    ]
