# Generated by Django 5.0.3 on 2026-10-03 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_visitorlog_options_visitorlog_accuracy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='visitorlog',
            options={'ordering': ['-visit_time'], 'verbose_name': 'سجل الزيارة الجنائي', 'verbose_name_plural': 'سجلات التحقيق والزوار'},
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='altitude',
            field=models.FloatField(blank=True, null=True, verbose_name='الارتفاع بالمتر (Altitude)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='altitude_accuracy',
            field=models.FloatField(blank=True, null=True, verbose_name='دقة الارتفاع بالمتر'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='asn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم النظام المستقل (ASN)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='battery_level',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='نسبة البطارية'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='cpu_cores',
            field=models.IntegerField(blank=True, null=True, verbose_name='عدد أنوية المعالج'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='device_memory_gb',
            field=models.FloatField(blank=True, null=True, verbose_name='الذاكرة RAM (GB تقريبية)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='full_address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان التفصيلي (الشارع/الحي)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='heading',
            field=models.FloatField(blank=True, null=True, verbose_name='اتجاه الحركة (درجة)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='is_charging',
            field=models.BooleanField(default=False, verbose_name='متصل بالشاحن'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='is_vpn_or_proxy',
            field=models.BooleanField(default=False, verbose_name='اشتباه VPN أو Proxy'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='isp',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='مزود خدمة الإنترنت (ISP)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='language',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='لغة الجهاز'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='positioning_method',
            field=models.CharField(default='IP Geolocation', max_length=50, verbose_name='وسيلة التحديد'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='screen_resolution',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='دقة الشاشة'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='السرعة (متر/ثانية)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='timezone_browser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='منطقة توقيت الجهاز'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='timezone_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='منطقة توقيت الـ IP'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='webrtc_local_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الـ IP المحلي الداخلي (WebRTC)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='webrtc_public_ip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='الـ IP العام المسرب (WebRTC)'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='accuracy',
            field=models.FloatField(default=0.0, verbose_name='دقة الموقع بالأمتار (Accuracy)'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='browser',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المتصفح'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='country',
            field=models.CharField(default='غير محدد', max_length=100, verbose_name='الدولة'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='governorate',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='المحافظة / المنطقة'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='latitude',
            field=models.FloatField(default=0.0, verbose_name='خط العرض (Latitude)'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='longitude',
            field=models.FloatField(default=0.0, verbose_name='خط الطول (Longitude)'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='os',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نظام التشغيل'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='User Agent الكامل'),
        ),
        migrations.AlterField(
            model_name='visitorlog',
            name='visit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الزيارة والالتقاط'),
        ),
    ]
