# Generated by Django 6.1.1 on 2026-10-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_clear_all_visitor_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='evidence_hash',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='الختم الرقمي للأدلة (SHA-256)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='gpu_renderer',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='معالج الرسوميات (GPU Renderer)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='is_automated_agent',
            field=models.BooleanField(default=False, verbose_name='بيئة وهمية أو روبوت (Bot/Headless)'),
        ),
        migrations.AddField(
            model_name='visitorlog',
            name='risk_score',
            field=models.IntegerField(default=0, verbose_name='درجة الخطورة والاشتباه (0-100)'),
        ),
    ]
